# A service call to carry out an inverse kinematics computation
# The inverse kinematics request
moveit_msgs/PositionIKRequest ik_request

---

# The returned solution
# (in the same order as the list of joints specified in the IKRequest message)
RobotStates solutions

moveit_msgs/MoveItErrorCodes error_code
